package im.tox.tox4j.impl.jni;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

/**
 * Mark methods that are to be generated by JniMethodImpls.
 *
 * <p>In {@link ToxCoreJni} and {@link ToxAvJni}, methods marked with this annotation do not need a manual
 * implementation in C++, as their JNI bridge implementations will be generated. This annotation exists only until the
 * majority of methods is generated, at which point there will be a "manual" override marker that inhibits
 * auto-generation. Ideally, all bridge method implementations will be generated, but in reality there are probably
 * going to be some complications that are too costly to overcome, so some manual overrides will remain.
 */
@Retention(RetentionPolicy.RUNTIME)
public @interface AutoGenerated {
  /**
   * Override the C function name this native method should call. By default, a method called e.g. toxFooBar will call
   * the C function tox_foo_bar. This can be overridden here.
   */
  String value() default "";
}
